## 2. NumPy Basics (Essential for Numerical Operations)

#### 1.Array Creation & Reshaping:

##### Create a 3x3 NumPy array with values ranging from 0 to 8.

In [6]:
import numpy as np
one_dimension=np.arange(0,9)
three_dimesnion=one_dimension.reshape(3,3)
print(three_dimesnion)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 1D array of 12 numbers, then reshape into 3 rows and 4 columns.

In [7]:
tweleve_numbers=np.arange(0,12)
reshaped_array=tweleve_numbers.reshape(3,4)
print(reshaped_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Create:

    a 2x3 array of all zeros

    a 3x1 array of all ones

    a 4x2 array filled with the number 9

In [14]:

# 2x3 array of all zeros
zero_arrays = np.zeros((2, 3))
print("2x3 Zeros:\n", zero_arrays)

# 3x1 array of all ones
ones_array = np.ones((3, 1))
print("3x1 Ones:\n", ones_array)

# 4x2 array filled with 9
nine_arrays = np.full((4, 2), 9)
print("4x2 Nines:\n", nine_arrays)


2x3 Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
3x1 Ones:
 [[1.]
 [1.]
 [1.]]
4x2 Nines:
 [[9 9]
 [9 9]
 [9 9]
 [9 9]]
